#------------------------------------------------------------------------------#
# This makefile was generated by Alessandro Bugatti                       #
#------------------------------------------------------------------------------#

IDIR =./include
CC=g++ 
CFLAGS=-I$(IDIR)
CPPFLAGS=-std=c++11

sas: $(OBJ)
	$(CC)  -o sas main.cpp src/*.cpp $(CFLAGS) $(CPPFLAGS)

